obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.18, 0.18], [0.18, -0.18], [-0.18, -0.18], [-0.18, 0.18]]
#robot_radius: ir_of_robot
inflation_radius: 0.2

observation_sources: laser_scan_sensor #point_cloud_sensor

laser_scan_sensor: {
sensor_frame: base_laser_link, 
data_type: LaserScan, 
topic: mybot/laser/scan, 
marking: true, 
clearing: true,
max_obstacle_height: 1.0,
min_obstacle_height: 0.0
}

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
